### ISSUE TITLE
Use case question, with efk

### ISSUE THREAD

**Issue by slimee** [floragunncom/search-guard-helm#10] opened 2019-03-10 19:42 UTC
Hi, thanks you for this work.

I am new to search-guard.
Is it possible to secure my efk deployment with this chart?

Thanks you

**Comment by floragunncom** [comment] 2019-03-11 12:50
You need to add the fluentd part (as daemonset i assume) but then i guess it should work

**Comment by slimee** [comment] 2019-03-11 18:07
Ok,

Do you mean fluentbit will need to auth into ES after search-guard deployment?

**Comment by floragunncom** [comment] 2019-03-12 21:37
Yes, either via basic authentication or client certificate or any other auth method Search Guard supports.

Will close this as it is not a bug.  Feel free to ask any question here: https://groups.google.com/forum/#!forum/search-guard

**Closed by floragunncom** 2019-03-12 21:37 UTC
